"""Gemini / Vertex AI client wrapper with a deterministic dry-run mode."""

from __future__ import annotations

import asyncio
from typing import Any

from .config import AppConfig


_DRY_RUN_TEMPLATE = """# This file was generated by AI Unit Test Assistant (dry-run).
# Review before committing.
import pytest


def test_generated_placeholder():
    assert True
"""


class LlmError(RuntimeError):
    """Raised when the LLM returns no usable response."""


class LlmClient:
    """Thin wrapper around ``google-genai`` with Vertex AI configuration.

    When ``config.dry_run`` is True, no network call is made and a deterministic
    placeholder test file is returned. This keeps tests cheap and offline.
    """

    def __init__(self, config: AppConfig):
        self._config = config
        self._client: Any | None = None

    def _ensure_client(self) -> Any:
        if self._client is not None:
            return self._client

        try:
            from google import genai  # type: ignore
        except ImportError as exc:  # pragma: no cover - import guarded at runtime
            raise LlmError(
                "google-genai is not installed; install the package or use --dry-run"
            ) from exc

        kwargs: dict[str, Any] = {}
        if self._config.google_cloud_project:
            kwargs["vertexai"] = True
            kwargs["project"] = self._config.google_cloud_project
            if self._config.google_cloud_location:
                kwargs["location"] = self._config.google_cloud_location
        self._client = genai.Client(**kwargs)
        return self._client

    async def generate(self, system_instruction: str, prompt: str) -> str:
        """Generate a response. In dry-run mode returns a fixed stub."""
        if self._config.dry_run:
            return _DRY_RUN_TEMPLATE

        client = self._ensure_client()
        loop = asyncio.get_running_loop()

        def _call() -> Any:
            return client.models.generate_content(  # type: ignore[no-any-return]
                model=self._config.gemini_model,
                contents=prompt,
                config={
                    "system_instruction": system_instruction,
                    "temperature": self._config.temperature,
                },
            )

        response = await loop.run_in_executor(None, _call)
        text = getattr(response, "text", None)
        if not text or not text.strip():
            raise LlmError("LLM returned an empty response")
        return text
