"""Main orchestration pipeline."""

from __future__ import annotations

from pathlib import Path

from .config import AppConfig
from .git_utils import get_changed_python_files
from .llm_client import LlmClient
from .models import FileResult, PipelineResult, SourceAnalysis, TestTarget
from .pytest_runner import run_pytest
from .report import write_json_report, write_markdown_report
from .source_analyzer import analyze_source_file, select_test_targets
from .test_finder import find_related_tests
from .test_generator import (
    ValidationError,
    generate_tests,
    repair_tests,
    update_existing_tests,
)


_GENERATED_HEADER = (
    "# This file was generated by AI Unit Test Assistant.\n"
    "# Review before committing.\n"
)

_SUGGESTED_HEADER = (
    "# This is a suggested update generated by AI Unit Test Assistant.\n"
    "# Review before replacing the original test file.\n"
)


def _generated_path_for(source_file: Path, output_dir: Path) -> Path:
    return output_dir / f"test_{source_file.stem}_generated.py"


def _suggested_path_for(
    test_file: Path, suggestions_dir: Path, repo_root: Path
) -> Path:
    try:
        rel = test_file.resolve().relative_to(repo_root.resolve())
    except ValueError:
        rel = Path(test_file.name)
    return suggestions_dir / rel


def _write_with_header(path: Path, header: str, code: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    body = code if code.endswith("\n") else code + "\n"
    path.write_text(header + body, encoding="utf-8")


async def _generate_and_repair(
    llm: LlmClient,
    config: AppConfig,
    analysis: SourceAnalysis,
    targets: list[TestTarget],
    related_tests_content: dict[Path, str],
    generated_path: Path,
) -> tuple[str, "object | None"]:
    """Generate tests and try to repair them if pytest fails.

    Returns ``(final_test_code, pytest_result)``.
    """
    test_code = await generate_tests(llm, analysis, targets, related_tests_content)
    _write_with_header(generated_path, _GENERATED_HEADER, test_code)

    pytest_result = run_pytest(config.repo_root, [generated_path])
    attempts = 0
    while not pytest_result.passed and attempts < config.repair_attempts:
        attempts += 1
        combined_output = (pytest_result.stdout or "") + "\n" + (pytest_result.stderr or "")
        try:
            repaired = await repair_tests(
                llm,
                analysis.source_code,
                test_code,
                combined_output,
            )
        except ValidationError:
            break
        test_code = repaired
        _write_with_header(generated_path, _GENERATED_HEADER, test_code)
        pytest_result = run_pytest(config.repo_root, [generated_path])

    return test_code, pytest_result


async def _process_file(
    config: AppConfig,
    llm: LlmClient,
    changed_file,
) -> FileResult:
    source_path = changed_file.path
    analysis = analyze_source_file(source_path, config.repo_root)
    targets = select_test_targets(analysis, changed_file.changed_lines)

    if not targets:
        return FileResult(
            source_file=source_path,
            status="skipped",
            message="No public functions or methods to test.",
        )

    related = find_related_tests(
        source_path, targets, config.repo_root, config.test_roots
    )
    related_content: dict[Path, str] = {}
    for path in related:
        try:
            related_content[path] = path.read_text(encoding="utf-8")
        except OSError:
            continue

    generated_path = _generated_path_for(source_path, config.output_dir)

    try:
        _, pytest_result = await _generate_and_repair(
            llm, config, analysis, targets, related_content, generated_path
        )
    except ValidationError as exc:
        return FileResult(
            source_file=source_path,
            status="error",
            message=f"Generated tests failed validation: {exc}",
        )
    except Exception as exc:  # noqa: BLE001 - per spec: keep processing other files
        return FileResult(
            source_file=source_path,
            status="error",
            message=f"Test generation failed: {exc}",
        )

    suggested_files: list[Path] = []
    if config.update_existing_tests:
        for test_path, existing_code in related_content.items():
            try:
                updated = await update_existing_tests(
                    llm, analysis, targets, test_path, existing_code
                )
            except ValidationError:
                continue
            except Exception:  # noqa: BLE001
                continue
            suggested = _suggested_path_for(
                test_path, config.suggestions_dir, config.repo_root
            )
            _write_with_header(suggested, _SUGGESTED_HEADER, updated)
            suggested_files.append(suggested)

    status = "passed" if pytest_result and pytest_result.passed else "failed"
    message = (
        "Generated tests passed."
        if status == "passed"
        else "Generated tests failed even after repair attempts."
    )
    return FileResult(
        source_file=source_path,
        generated_test_file=generated_path,
        suggested_test_files=suggested_files,
        pytest_result=pytest_result,
        status=status,
        message=message,
    )


async def run_pr_assistant(config: AppConfig) -> PipelineResult:
    """Run the full PR assistant pipeline."""
    changed_files = get_changed_python_files(
        config.repo_root, config.base_ref, config.exclude_paths
    )

    llm = LlmClient(config)
    file_results: list[FileResult] = []

    for changed_file in changed_files:
        try:
            result = await _process_file(config, llm, changed_file)
        except Exception as exc:  # noqa: BLE001 - keep going on per-file failures
            result = FileResult(
                source_file=changed_file.path,
                status="error",
                message=f"Unhandled error: {exc}",
            )
        file_results.append(result)

    pipeline_result = PipelineResult(
        changed_files=[cf.path for cf in changed_files],
        file_results=file_results,
    )

    write_markdown_report(pipeline_result, config.report_path, config.repo_root)
    write_json_report(pipeline_result, config.report_path, config.repo_root)
    return pipeline_result


async def run_generate_tests_for_file(config: AppConfig, source: Path) -> FileResult:
    """Generate tests for a single source file (used by ``generate-tests`` command)."""
    analysis = analyze_source_file(source, config.repo_root)
    targets = select_test_targets(analysis, set())
    if not targets:
        return FileResult(
            source_file=source,
            status="skipped",
            message="No public functions or methods to test.",
        )

    llm = LlmClient(config)
    related = find_related_tests(source, targets, config.repo_root, config.test_roots)
    related_content: dict[Path, str] = {}
    for path in related:
        try:
            related_content[path] = path.read_text(encoding="utf-8")
        except OSError:
            continue

    generated_path = _generated_path_for(source, config.output_dir)
    try:
        _, pytest_result = await _generate_and_repair(
            llm, config, analysis, targets, related_content, generated_path
        )
    except ValidationError as exc:
        return FileResult(
            source_file=source,
            status="error",
            message=f"Generated tests failed validation: {exc}",
        )

    status = "passed" if pytest_result and pytest_result.passed else "failed"
    return FileResult(
        source_file=source,
        generated_test_file=generated_path,
        pytest_result=pytest_result,
        status=status,
        message=(
            "Generated tests passed."
            if status == "passed"
            else "Generated tests failed even after repair attempts."
        ),
    )
