"""Tests for apply_suggested_updates."""

from __future__ import annotations

from pathlib import Path

from ai_test_assistant.pipeline import apply_suggested_updates


_SUGGESTED = (
    "# This is a suggested update generated by AI Unit Test Assistant.\n"
    "# Review before replacing the original test file.\n"
    "import pytest\n\n"
    "def test_thing():\n"
    "    assert True\n"
)


def test_copies_files_to_matching_paths(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    (repo / "tests").mkdir(parents=True)
    (repo / "tests" / "test_old.py").write_text("# old\n", encoding="utf-8")

    sugg = tmp_path / "suggestions"
    (sugg / "tests").mkdir(parents=True)
    (sugg / "tests" / "test_old.py").write_text(_SUGGESTED, encoding="utf-8")

    applied = apply_suggested_updates(sugg, repo)

    assert len(applied) == 1
    target = repo / "tests" / "test_old.py"
    content = target.read_text(encoding="utf-8")
    # Header stripped, real test code preserved.
    assert "# This is a suggested update" not in content
    assert "def test_thing" in content


def test_keep_header_when_requested(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    sugg = tmp_path / "suggestions"
    (sugg / "tests").mkdir(parents=True)
    (sugg / "tests" / "test_a.py").write_text(_SUGGESTED, encoding="utf-8")

    apply_suggested_updates(sugg, repo, strip_header=False)

    content = (repo / "tests" / "test_a.py").read_text(encoding="utf-8")
    assert content.startswith(
        "# This is a suggested update generated by AI Unit Test Assistant."
    )


def test_returns_empty_when_suggestions_dir_missing(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    sugg = tmp_path / "does-not-exist"

    applied = apply_suggested_updates(sugg, repo)

    assert applied == []


def test_creates_intermediate_directories(tmp_path: Path) -> None:
    repo = tmp_path / "repo"
    sugg = tmp_path / "suggestions"
    nested = sugg / "tests" / "sub" / "pkg"
    nested.mkdir(parents=True)
    (nested / "test_deep.py").write_text(_SUGGESTED, encoding="utf-8")

    apply_suggested_updates(sugg, repo)

    target = repo / "tests" / "sub" / "pkg" / "test_deep.py"
    assert target.exists()
    assert "def test_thing" in target.read_text(encoding="utf-8")
